### ISSUE TITLE
Cutting a new release?

### ISSUE THREAD

**Issue by jonahbeckford** [rgrinberg/curly#10]
I've got https://github.com/rgrinberg/curly/pull/8 and https://github.com/rgrinberg/curly/pull/6 in a Windows (DKML) opam repository, but it would be great if those were also in the main opam repository.

Can a new release be made?

**Comment by rgrinberg** [comment]
I've added you as a collaborator. Feel free to make a release.

**Comment by emillon** [comment]
I can give a hand with the release as well if needed.

**Comment by bikallem** [comment]
Please include https://github.com/rgrinberg/curly/pull/12 on the new release.

**Comment by jonahbeckford** [comment]
Ah. There is almost no chance I'll be able to do a release myself. Well ... not for the next few months. I suspect we both have high tens of packages to maintain so the ask makes a lot of sense.

Does anyone else want to cut this particular release?

**Comment by emillon** [comment]
Sure, I'll do that by the end of the week.

**Comment by emillon** [comment]
https://github.com/ocaml/opam-repository/pull/23020

**Comment by bikallem** [comment]
Thanks.
